service: fn-get-by-name

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: 
functions:
  getByName:
    handler: src/handler/get-by-name-handler.handler
    events:
      - http:
          path: api/name/{name}
          method: get
  getCharacters:
    handler: src/handler/get-characters-handler.handler
    events:
      - http:
          path: api/characters
          method: get
  createCharacter:
    handler: src/handler/create-character-handler.handler
    events:
      - http:
          path: api/character
          method: post
plugins:
  - serverless-offline